<?php echo $before_widget; ?>
<?php echo $before_title . $title . $after_title ?>

<div class="bf3infobox-widget" style="text-align: center">
<p>
    <?php if(isset($options['display_playername'])) : ?>
        <a href="http://bf3stats.com/stats_<?php echo strtolower($data['plat']) ?>/<?php echo $data['name'] ?>/"
           target="_blank" class="rankimagelink"><img src="<?php echo plugins_url( 'img/'.$data['stats']['rank']['img_medium'] , dirname(__FILE__) ) ?>"
         title="Rank <?php echo $data['stats']['rank']['nr'] ?>"
         style="margin-top: 5px;"></a>
    <?php else: ?>
        <img src="<?php echo plugins_url( 'img/'.$data['stats']['rank']['img_medium'] , dirname(__FILE__) ) ?>"
         title="Rank <?php echo $data['stats']['rank']['nr'] ?>"
         style="margin-top: 5px;">
    <?php endif; ?>
    <br>

    <?php echo $data['stats']['rank']['name'] ?><br>

    <?php if(isset($options['display_playername'])) : ?>
        <?php echo $data['name'] ?> -
    <?php endif; ?>

    Rank <?php echo $data['stats']['rank']['nr'] ?>

    <?php if(isset($options['display_platform'])) : ?>
        - <?php echo strtoupper($data['plat']) ?>
    <?php endif; ?>
</p>

<!-- not ready yet
    <table>
        <tr>
            <td>
                <img src="http://files.bf3stats.com/img/<?php echo $data['country_img'] ?>" alt="<?php echo $data['country_name'] ?>" title="<?php echo $data['country_name'] ?>">
            </td>
        </tr>
    </table>
-->

<?php if(isset($options['display_generalstats']) OR isset($options['display_tillnextrank'])) : ?>
    <table>

    <?php if(isset($options['display_tillnextrank'])) : ?>
        <tr>
            <td colspan="5" class="center">
            <?php
                $rankscore = $data['stats']['nextranks'][0]['score'] - $data['stats']['rank']['score'];
                $progress = round(($rankscore - $data['stats']['nextranks'][0]['left']) / ($rankscore / 100), 0).'%';
                $pointsleft = $data['stats']['nextranks'][0]['left'];
                printf(__('Progress: %s, %d left', 'bf3infobox'), $progress, $pointsleft);
            ?>
            </td>
        </tr>
    <?php endif; ?>


    <?php if(isset($options['display_generalstats'])) : ?>
        <tr class="odd">
            <td>
                <img src="<?php echo plugins_url( 'img/misc/Mp_Main_KillsDeathsRatio_bk.png' , dirname(__FILE__) ) ?>"
                     alt="<?php echo __('Kill/Death Ratio', 'bf3infobox'); ?>" title="<?php echo __('Kill/Death Ratio', 'bf3infobox'); ?>" width="24" style="max-width: 24px">
            </td>
            <td><?php echo round($data['stats']['global']['kills'] / $data['stats']['global']['deaths'], 2); ?></td>

            <td>&nbsp;</td>

            <td>
                <img src="<?php echo plugins_url( 'img/misc/Mp_WLR_Win_Loss_Ratio_bk.png' , dirname(__FILE__) ) ?>"
                     alt="<?php echo __('Win/Loss Ratio', 'bf3infobox'); ?>" title="<?php echo __('Win/Loss Ratio', 'bf3infobox'); ?>" width="24" style="max-width: 24px">
            </td>
            <td><?php echo round($data['stats']['global']['wins'] / $data['stats']['global']['losses'], 2); ?></td>
        </tr>


        <tr>
            <td>
                <img src="<?php echo plugins_url( 'img/misc/Mp_Accuracy_Accuracy_bk.png' , dirname(__FILE__) ) ?>"
                     alt="<?php echo __('Accuracy', 'bf3infobox'); ?>" title="<?php echo __('Accuracy', 'bf3infobox'); ?>" width="24" style="max-width: 24px">
            </td>
            <td><?php
                // echo round($data['stats']['global']['hits'] / ($data['stats']['global']['shots'] / 100 ), 2);
                // using team us+ru hits/shots for infantry accuracy (like battlelog) instead of global accuracy
                echo round(
                    ($data['stats']['teams']['US']['hits'] + $data['stats']['teams']['RU']['hits']) * 100
                    / ($data['stats']['teams']['US']['shots'] + $data['stats']['teams']['RU']['shots'])
                    , 2);
                ?>%</td>

            <td>&nbsp;</td>

            <td>
                <img src="<?php echo plugins_url( 'img/misc/Mp_Main_ScorePerMinute_bk.png' , dirname(__FILE__) ) ?>"
                     alt="<?php echo __('Score per Minute', 'bf3infobox'); ?>" title="<?php echo __('Score per Minute', 'bf3infobox'); ?>" width="24" style="max-width: 24px">
            </td>
            <td><?php echo round($data['stats']['scores']['score'] / ($data['stats']['global']['time'] / 60 ), 2); ?></td>
        </tr>


        <tr class="odd">
            <td>
                <img src="<?php echo plugins_url( 'img/misc/Mp_Kill_Streak_Kill_Streak_bk.png' , dirname(__FILE__) ) ?>"
                     alt="<?php echo __('Longest Kill Streak', 'bf3infobox'); ?>" title="<?php echo __('Longest Kill Streak', 'bf3infobox'); ?>" width="24" style="max-width: 24px">
            </td>
            <td><?php echo $data['stats']['global']['killstreakbonus']; ?></td>

            <td>&nbsp;</td>

            <td>
                <img src="<?php echo plugins_url( 'img/misc/Mp_Marksman_Longest_Headshot_bk.png' , dirname(__FILE__) ) ?>"
                     alt="<?php echo __('Longest Headshot', 'bf3infobox'); ?>" title="<?php echo __('Longest Headshot', 'bf3infobox'); ?>" width="24" style="max-width: 24px">
            </td>
            <td><?php echo $data['stats']['global']['longesths'] ?>m</td>
        </tr>
    <?php endif; ?>

    </table>
<?php endif; ?>


    <?php if(isset($options['display_playername'])) : ?>
    <p><a href="http://bf3stats.com/stats_<?php echo strtolower($data['plat']) ?>/<?php echo $data['name'] ?>/"
               target="_blank"><?php echo __('more statistics', 'bf3infobox'); ?></a></p>
    <?php endif; ?>

</div>

<?php echo $after_widget; ?>